export const config = {
  port: parseInt(process.env.PORT || '3000'),
  googleApiKey: process.env.GOOGLE_API_KEY || '',
  qdrantUrl: process.env.QDRANT_URL || 'http://localhost:6333',
  corsOrigin: process.env.CORS_ORIGIN || 'http://localhost:5173',
  uploadDir: process.env.UPLOAD_DIR || './uploads',
  dbPath: process.env.DB_PATH || './data/rag.db',
  qdrantCollection: 'documents',
  chunkSize: 600,
  chunkOverlap: 100,
  embeddingModel: 'gemini-embedding-001',
  embeddingDimensions: 3072,
  llmModel: 'gemini-2.5-flash',
  topK: 3,
};
